// ============================================================
// PHOTO DATA — edit this to add your photos
// ============================================================
// Drop images into /public/photos/ and update src paths below

export interface Photo {
  id: number
  src: string
  title: string
  camera: string
  film: string
  location: string
  date: string
  description: string
}

export const PHOTOS: Photo[] = [
  {
    id: 1,
    src: '/photos/film-bella.jpeg',
    title: 'Bella',
    camera: 'Canon AF35M',
    film: 'Superia 400',
    location: 'Home',
    date: 'April 2020',
    description: 'My dog Bella when she was a puppy.',
  },
  {
    id: 2,
    src: '/photos/small-shrine.JPG',
    title: 'A small and intimate temple.',
    camera: 'Fuji X100V',
    location: 'Kyoto, Japan',
    film: 'Porta 180 Simulation',
    date: 'January 2026',
    description: 'A temple hidden further up a hill.',
  },
  {
    id: 3,
    src: '/photos/fuji-kayla.jpg',
    title: 'Early in the morning',
    camera: 'Fuji X100V',
    film: 'Porta 180 Simulation',
    location: 'Kyoto, Japan',
    date: 'January 2026',
    description: 'Test shots before a surprise engagement shoot.',
  },
  {
    id: 4,
    src: '/photos/film-deer.JPG',
    title: 'Feeding the Nara deer',
    camera: 'Canon Rebel 2000',
    film: 'Fujicolor 35mm (Expired 2005)',
    location: 'Nara, Japan',
    date: 'August 2024',
    description: 'This deer nipped my shirt not too long after this',
  },
  {
    id: 5,
    src: '/photos/film-kayla1.JPG',
    title: 'Coffee date',
    camera: 'Canon AF35M',
    film: 'Superia 400',
    location: 'Malibu, CA',
    date: 'August 2019',
    description: 'Kayla and I on a coffee date.',
  },
  {
    id: 6,
    src: '/photos/film-kayla2.JPG',
    title: 'A walkway in Japan',
    camera: 'Canon AF35M',
    film: 'Fujicolor 35mm (Expired 2005)',
    location: 'Osaka, Japan',
    date: 'August 2024',
    description: 'Found this nice walkway after the Ghibli museum.',
  },
  {
    id: 7,
    src: '/photos/film-kyoto.JPG',
    title: 'Kyoto Temple',
    camera: 'Canon AF35M',
    film: 'Fujicolor 35mm (Expired 2005)',
    location: 'Kyoto, Japan',
    date: 'August 2024',
    description: 'Took a long walk to get to this spot.',
  },
  {
    id: 8,
    src: '/photos/film-ryan-michael.jpg',
    title: 'Ryan and Michael',
    camera: 'Canon AF35M',
    film: 'Superia 400',
    location: 'Los Angeles, CA',
    date: 'May 2023',
    description: 'During a friend\'s wedding at Yonder Coffee.',
  },
  {
    id: 9,
    src: '/photos/film-steeb-mart.jpg',
    title: 'Steeb and Mart',
    camera: 'Canon AF35M',
    film: 'Superia 400',
    location: 'Los Angeles, CA',
    date: 'May 2023',
    description: 'Esteban and Marti at a friend\'s wedding at Yonder Coffee.',
  },
  {
    id: 10,
    src: '/photos/film-therese-kayla.jpg',
    title: 'Kayla and Therese',
    camera: 'Canon AF35M',
    film: 'Superia 400',
    location: 'Los Angeles, CA',
    date: 'May 2023',
    description: 'Kayla with the bride on the wedding day at Yonder Coffee.',
  },
  {
    id: 11,
    src: '/photos/fuji-friend.JPG',
    title: 'Friends at another wedding',
    camera: 'Fuji X100V',
    film: 'Porta 180 Simulation',
    location: 'Los Angeles, CA',
    date: 'July 2025',
    description: 'Friends at another wedding.',
  },
  {
    id: 12,
    src: '/photos/fuji-meat.jpg',
    title: 'My niece',
    camera: 'Fuji X100V',
    film: 'Porta 180 Simulation',
    location: 'Big Bear, CA',
    date: 'February 2025',
    description: 'My niece shortly after walking a little (she\s okay).',
  },
  {
    id: 13,
    src: '/photos/fuji-red-kaylab.jpg',
    title: 'Post-engagement',
    camera: 'Fuji X100V',
    film: 'Porta 180 Simulation',
    location: 'Kyoto, Japan',
    date: 'January 2026',
    description: 'Reed and Kayla at the surprise engagement shoot.',
  },
  {
    id: 14,
    src: '/photos/fuji-ysa.jpg',
    title: 'My sister on a cousin trip',
    camera: 'Fuji X100V',
    film: 'Porta 180 Simulation',
    location: 'Los Angeles, CA',
    date: 'June 2025',
    description: 'My sister and I on a cousin trip.',
  },
  {
    id: 15,
    src: '/photos/rooftop-kayla.JPG',
    title: 'Rooftop Garden',
    camera: 'Fuji X100V',
    film: 'Porta 180 Simulation',
    location: 'Osaka, Japan',
    date: 'January 2026',
    description: 'Kayla and I on a cute date on a rooftop garden.',
  },
  {
    id: 16,
    src: '/photos/temple-character.JPG',
    title: 'Daruma doll',
    camera: 'Fuji X100V',
    film: 'Porta 180 Simulation',
    location: 'Kyoto, Japan',
    date: 'January 2026',
    description: 'This daruma\s predication was tied like a scarf.',
  },
]
