server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=portfolio_user
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
app.cors.allowed-origins=http://localhost:5173,http://localhost:5174
app.contact.recipient-email=j.julian.lozada@gmail.com
app.canvas.max-pixels-per-day=500
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=j.julian.lozada@gmail.com
spring.mail.password=msdqmwopzymmkveb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true